name: Build and Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --icon=Lotus.ico LotusSideBar.py

    - name: Create ZIP file
      run: |
        mkdir output
        cp dist/LotusSideBar.exe output/
        cp Lotus.png output/
        powershell Compress-Archive -Path output/* -DestinationPath LotusSideBar.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: LotusSideBar
        path: LotusSideBar.zip
